services:
  db:
    image: postgres:16
    container_name: ledger-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger
      POSTGRES_DB: ledger
    ports:
      - "5432:5432"
    volumes:
    #ensures data is safe even if the container is removed
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
